pack_and_copy: 
    script:
    - 'MOD_VER=`modver info.json`'
    - 'MOD_NAME=`echo "dytech-core_$MOD_VER"`'
    - 'MOD_FILE=`echo "dytech-core_$MOD_VER.zip"`'
    - 'ln -s . $MOD_NAME'
    - 'zip -r $MOD_FILE $MOD_NAME/graphics $MOD_NAME/locale $MOD_NAME/prototypes $MOD_NAME/script-locale $MOD_NAME/scripts $MOD_NAME/data.lua $MOD_NAME/data-updates.lua $MOD_NAME/data-final-fixes.lua $MOD_NAME/control.lua $MOD_NAME/config.lua $MOD_NAME/info.json'
    - 'rm $MOD_NAME'
    - 'mv $MOD_FILE /var/factorio/factorio/mods'
    - 'cd /var/factorio/factorio'
    - 'echo "Removing old factorio save..."'
    - 'rm -f saves/dytech-core.zip'
    - 'echo "Creating new factorio save..."'
    - './bin/x64/factorio --create saves/dytech-core.zip'
    - 'echo "Running factorio..."'
    - './bin/x64/factorio --start-server saves/dytech-core.zip --until-tick 300'